//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooEnot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> ItemSet { get; set; }
        public virtual DbSet<Type> TypeSet { get; set; }
        public virtual DbSet<Poz2> Poz2Set1 { get; set; }
        public virtual DbSet<Bill> BillSet { get; set; }
        public virtual DbSet<Client> ClientSet { get; set; }
        public virtual DbSet<Shop> ShopSet { get; set; }
        public virtual DbSet<Stock> StockSet { get; set; }
        public virtual DbSet<Invoice> InvoiceSet { get; set; }
        public virtual DbSet<Seller> SellerSet { get; set; }
        public virtual DbSet<Poz1> Poz1Set { get; set; }
    }
}
