//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooEnot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poz1
    {
        public int Poz1Id { get; set; }
        public int ItemId { get; set; }
        public int Count { get; set; }
        public decimal Price { get; set; }
        public int InvoiceId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
