//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooEnot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int ShopId { get; set; }
        public int Count { get; set; }
        public int MinCount { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
